sudo: required
services:
    - docker

before_install:
    - docker build -t deepak/react-app -f Dockerfile.dev .

script:
    - docker run deepak/react-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "docker-env"
    bucket_name: "deepakkaushik321"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
